2024-12-17 19:04:51,217 - root - DEBUG - Starting GoPro Control Interface
2024-12-17 19:04:58,174 - asyncio - DEBUG - Using proactor: IocpProactor
2024-12-17 19:04:58,181 - root - INFO - Searching for GoPro cameras...
2024-12-17 19:04:58,413 - root - INFO - Discovered GoPro: C3461350386740._gopro-web._tcp.local. at 172.27.140.51
2024-12-17 19:04:58,427 - root - INFO - Discovered GoPro: C3461326143885._gopro-web._tcp.local. at 172.28.185.51
2024-12-17 19:05:03,196 - root - INFO - Setting preset on all cameras...
2024-12-17 19:05:03,207 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 19:05:03,207 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 19:05:03,287 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/presets/set_group?id=0 HTTP/11" 400 3
2024-12-17 19:05:03,287 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/presets/set_group?id=0 HTTP/11" 400 3
2024-12-17 19:05:03,288 - root - ERROR - Failed to set preset on camera 172.27.140.51. Status Code: 400
2024-12-17 19:05:03,290 - root - ERROR - Failed to set preset on camera 172.28.185.51. Status Code: 400
2024-12-17 19:05:17,300 - root - ERROR - Error running script goprolist_usb_activate_time_sync.py: Command 'goprolist_usb_activate_time_sync.py' returned non-zero exit status 1.
