2024-12-17 18:49:08,553 - asyncio - DEBUG - Using proactor: IocpProactor
2024-12-17 18:49:08,664 - root - INFO - Searching for GoPro cameras...
2024-12-17 18:49:08,909 - root - INFO - Discovered GoPro: C3461350386740._gopro-web._tcp.local. at 172.27.140.51
2024-12-17 18:49:08,910 - root - INFO - Discovered GoPro: C3461326143885._gopro-web._tcp.local. at 172.28.185.51
2024-12-17 18:49:13,765 - root - INFO - Found the following GoPro devices:
2024-12-17 18:49:13,769 - root - INFO - Name: C3461350386740._gopro-web._tcp.local., IP: 172.27.140.51
2024-12-17 18:49:13,770 - root - INFO - Name: C3461326143885._gopro-web._tcp.local., IP: 172.28.185.51
2024-12-17 18:49:13,773 - root - INFO - Cache updated successfully with newly discovered devices.
2024-12-17 18:49:13,774 - root - INFO - Resetting and enabling USB control on all cameras...
2024-12-17 18:49:13,776 - root - INFO - Resetting USB control on camera 172.27.140.51.
2024-12-17 18:49:13,778 - root - INFO - Resetting USB control on camera 172.28.185.51.
2024-12-17 18:49:13,790 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 18:49:13,791 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 18:49:13,856 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/control/wired_usb?p=0 HTTP/11" 500 3
2024-12-17 18:49:13,856 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/control/wired_usb?p=0 HTTP/11" 200 3
2024-12-17 18:49:13,857 - root - ERROR - Failed to disable USB control on camera 172.27.140.51. Status Code: 500. Response: {}

2024-12-17 18:49:13,857 - root - INFO - USB control disabled on camera 172.28.185.51.
2024-12-17 18:49:15,860 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 18:49:15,864 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 18:49:15,939 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/control/wired_usb?p=1 HTTP/11" 500 3
2024-12-17 18:49:15,941 - root - ERROR - Failed to enable USB control on camera 172.27.140.51. Status Code: 500. Response: {}

2024-12-17 18:49:15,955 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/control/wired_usb?p=1 HTTP/11" 200 3
2024-12-17 18:49:15,956 - root - INFO - USB control enabled on camera 172.28.185.51.
2024-12-17 18:49:15,957 - root - INFO - Synchronizing time on all cameras...
2024-12-17 18:49:15,962 - root - ERROR - Failed to sync time: cannot import name 'sync_time' from 'date_time_sync' (c:\!AndriiShramko\inventions\SDKGOPROShramko\GoProControl\api\v2\v39\date_time_sync.py)
2024-12-17 18:49:15,964 - root - ERROR - An error occurred: cannot import name 'sync_time' from 'date_time_sync' (c:\!AndriiShramko\inventions\SDKGOPROShramko\GoProControl\api\v2\v39\date_time_sync.py)
